### ISSUE TITLE
Specifying the password on the command line is a security risk

### ISSUE THREAD

**Issue by mlell** [johann-petrak/python-tiny-http-server#2]
When calling `tiny-http-server --auth USER:PASS`, this command line is visible to other users on the same machine by programs like htop. This might give away the password also for other uses, if the respective user uses the password in multiple locations. 

Maybe using an environment variable, or saving the password hash in a file might mitigate this. 

Example saving password in file: [script writing the password](https://github.com/mlell/singularity-r/blob/master/scripts/inside/rstudio_passwd.py), [script verifying the password](https://github.com/mlell/singularity-r/blob/master/scripts/inside/rstudio_auth_file.py)

**Comment by mlell** [comment]
... just noted the `--authfile` option, sorry, missed that. Still might be worth to mention that in docs..?

**Comment by johann-petrak** [comment]
Yes, I thought that this was clear, but maybe a good idea to mention it, I have added a note to the README.
