### ISSUE TITLE
upload file feature request

### ISSUE THREAD

**Issue by asmwarrior** [johann-petrak/python-tiny-http-server#3]
Hi, this is a nice project, I just searched by Google, and found here: https://pypi.org/project/tiny-http-server/

While, I see some people already did some upload feature, see here:
[RDCH106/Simple-File-Server](https://github.com/RDCH106/Simple-File-Server), my fork to support python3 is here: [Simple-File-Server](https://github.com/asmwarrior/Simple-File-Server), so I hope your project can also have the upload feature, thanks!

**Comment by johann-petrak** [comment]
If the Simple-File-Server project does what you need, maybe it is better and more useful to you and you would prefer using it?
I was not aware of that project when I implemented the tiny-http-server

Update: I just tested the upload function of your fork of Simple-File-Server and always get a bad request error.

**Comment by asmwarrior** [comment]
> If the Simple-File-Server project does what you need, maybe it is better and more useful to you and you would prefer using it? I was not aware of that project when I implemented the tiny-http-server

There are a lot of issues in that Simple-File-Server project, and it only support a single user name and password, while your code is more compact and easy to understand, and support multiply user names and passwords.

> 
> Update: I just tested the upload function of your fork of Simple-File-Server and always get a bad request error.

Yes, I also see such issue, and I really don't know how to fix it.  The Simple-File-Server project is a bit complex for me.

**Comment by asmwarrior** [comment]
I searched for a while, and maybe this code can help to do the upload:
[uploadserver/__init__.py at master · Densaugeo/uploadserver](https://github.com/Densaugeo/uploadserver/blob/master/uploadserver/__init__.py)

EDIT: from this project: [uploadserver · PyPI](https://pypi.org/project/uploadserver/)

**Comment by johann-petrak** [comment]
Thanks - I will have a look and decide if it is feasible to add this feature. If at all, it will only be optional, as it opens all kinds of different security threats and attack vectors.

**Comment by johann-petrak** [comment]
Implemented as of 31d2f7e42a91ce03df9ee6fc4c1eede4be6bba77 - please test.

**Comment by asmwarrior** [comment]
Thanks.

I got an error when running the script:

~~~~
Traceback (most recent call last):
  File "F:\code\python-tiny-http-server\tiny_http_server\server.py", line 407, in <module>
    main()
  File "F:\code\python-tiny-http-server\tiny_http_server\server.py", line 357, in main
    signal.signal(signal.SIGHUP, mysignalhandler)
AttributeError: module 'signal' has no attribute 'SIGHUP'
~~~~

I searched the error, and found that SIGHUP is Linux related symbol, it does not exist on Windows.

**Comment by johann-petrak** [comment]
Ah, I did not think of that and since I am not using Windows did not experience that problem.
I removed this in the latest commit, please try again :)

**Comment by asmwarrior** [comment]
OK, the upload feature works correctly. Thanks.

BTW: I think you can make some OS conditional check of the system. Note just remove the code in your commit [Remove signal handler, not portable.](https://github.com/johann-petrak/python-tiny-http-server/commit/6fdddcbb04f3067279a8455e5893a54902485dff). Just like the answers in this post: [python module 'signal' has no attribute 'SIGHUP' and other signals](https://stackoverflow.com/questions/58787330/python-module-signal-has-no-attribute-sighup-and-other-signals)

I'm going to use your project in a Linux server in the intranet.

**Comment by johann-petrak** [comment]
Catching SIGHUB was just a test of mine and is not really necessary. 
Thanks for testing, I will close this now, if there are new issues, feel free to open another issue.
