### ISSUE TITLE
Using Basic Authentication does not work under HTTP

### ISSUE THREAD

**Issue by asmwarrior** [johann-petrak/python-tiny-http-server#4]
Hi, I just read the homepage readme file, it said:

> Whenever at least one user/password pair is added through either the --auth option or as line in the file specified via --authfile, basic authentication is enabled. This can be combined with HTTPs (see below).

While, in my test(Windows 7 64bit, and Python 3.8, Firefox 103)

When I run the command with the option: (from the spyder IDE)

```
In [3]: runfile('F:/file-server2/python-tiny-http-server/tiny_http_server/server.py', args='--authfile user.txt', wdir='F:/file-server2/python-tiny-http-server/tiny_http_server')
Serving HTTP on 127.0.0.1 port 8000 (http://127.0.0.1:8000/) ...
```
My user.txt file has such contents:
~~~~
abc:123
xyz:456
a:1
b:2
c:3
~~~~

I see Firefox can directly open the webpage, and I don't need to enter the username and password.

Are there anything wrong?
Thanks.

**Comment by johann-petrak** [comment]
This should work, though I do not know how things work under Windows (I only use Linux) or how calling from spyder works.

Could you please test again with the current development version? If you still have problems, could you add the "--debug" option to the call and share the console output?

**Comment by asmwarrior** [comment]
Hi, I checked this issue again. At first, I run the command without the `--authfile`, and at second step, I run the command with `--authfile` option. Under Spyder(Windows 7 64bit), it looks like the old server is not stopped correctly or maybe the Firefox browser saved my entered user name and password, so I can directly open the web page at the second step.

Anyway, I believe this is not the issue of your server code, I will close the issue, once it happens again, I will reopen it.

**Comment by asmwarrior** [comment]
BTW:

I got this info when I start the command again:

~~~~
INFO:MODSLAVE/18870:listener closed
INFO:MODSLAVE/18870:server has terminated
Command Line : --authfile user.txt
INFO:tiny-http-server:Serving HTTP on 127.0.0.1, port 8000 (http://127.0.0.1:8000/) ...
~~~~

So, this log message means the old server got closed, and the new server with the new option started again. I haven't see this before, so this may be caused by your recent commits.

**Comment by johann-petrak** [comment]
Yes, terminating the server currently requires Ctrl-C or killing it.

Previously, if the server was terminated and then restarted with the same auth file, a user that was previously logged into the same Firefox instance would not have to authenticate again.

However, with the current version this should NOT happen anymore: if firefox is connecting to a newly restarted server, the credentials should be necessary!

**Comment by johann-petrak** [comment]
> BTW:
> 
> I got this info when I start the command again:
> 
> ```
> INFO:MODSLAVE/18870:listener closed
> INFO:MODSLAVE/18870:server has terminated
> ```
> 
These messages are definitely not coming from my program and I am pretty sure also not from python library I am using.

**Comment by johann-petrak** [comment]
As far as I understand you can interrupt the server by pressing Ctrl-C within the Console window inside Spyder.

**Comment by asmwarrior** [comment]
> As far as I understand you can interrupt the server by pressing Ctrl-C within the Console window inside Spyder.

Thanks for the tip.
Ctrl-C can stop the server.

In my test two days ago, it looks like I have to close the "IPython Process"(usually named Console 1/A) inside the Spyder, and Spyder will automatically create a new shell named "Console 2/A" to let the server start correctly. (So the console name will go to "Console 3/A", "Console 4/A" every time I want to start the server.

Maybe there are something wrong with the Spyder, maybe the server/resource is not killed by the "Ctrl-C". Today, I switched to use another IDE named PyScripter, and it won't let me start the IPython shell, and the log message in the post https://github.com/johann-petrak/python-tiny-http-server/issues/4#issuecomment-1227244866 were from the Pyscripter IDE's shell.
